import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from './_components/Navbar/Navbar';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ja'>
      <Navbar />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
